CREATE TABLE public.cities (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name character varying(100) NOT NULL,
    description character varying(500),
    province_id uuid NOT NULL,
    image_url character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone NULL,
    CONSTRAINT cities_pkey PRIMARY KEY (id),
    CONSTRAINT cities_province_id_fkey FOREIGN KEY (province_id) REFERENCES public.provinces (id) ON DELETE CASCADE,
    CONSTRAINT cities_unique_name_in_province UNIQUE (name, province_id)
);

-- Complete list of cities/regencies for all Indonesian provinces
WITH provinces AS (
  SELECT id, name FROM public.provinces
)
INSERT INTO public.cities (id, name, province_id, image_url) VALUES 
  -- ACEH
  (gen_random_uuid(), 'Banda Aceh', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Banda+Aceh'),
  (gen_random_uuid(), 'Langsa', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Langsa'),
  (gen_random_uuid(), 'Lhokseumawe', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Lhokseumawe'),
  (gen_random_uuid(), 'Sabang', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Sabang'),
  (gen_random_uuid(), 'Subulussalam', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Subulussalam'),
  (gen_random_uuid(), 'Aceh Besar', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Besar'),
  (gen_random_uuid(), 'Aceh Barat', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Barat'),
  (gen_random_uuid(), 'Aceh Selatan', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Selatan'),
  (gen_random_uuid(), 'Aceh Utara', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Utara'),
  (gen_random_uuid(), 'Aceh Timur', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Timur'),
  (gen_random_uuid(), 'Aceh Tengah', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Tengah'),
  (gen_random_uuid(), 'Aceh Tenggara', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Tenggara'),
  (gen_random_uuid(), 'Gayo Lues', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Gayo+Lues'),
  (gen_random_uuid(), 'Pidie', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Pidie'),
  (gen_random_uuid(), 'Pidie Jaya', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Pidie+Jaya'),
  (gen_random_uuid(), 'Bener Meriah', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Bener+Meriah'),
  (gen_random_uuid(), 'Simeulue', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Simeulue'),
  (gen_random_uuid(), 'Aceh Jaya', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Aceh+Jaya'),
  (gen_random_uuid(), 'Nagan Raya', (SELECT id FROM provinces WHERE name = 'Aceh'), 'https://placehold.co/600x400.jpg?text=Nagan+Raya'),

  -- SUMATERA UTARA
  (gen_random_uuid(), 'Medan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Medan'),
  (gen_random_uuid(), 'Binjai', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Binjai'),
  (gen_random_uuid(), 'Tebing Tinggi', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Tebing+Tinggi'),
  (gen_random_uuid(), 'Pematangsiantar', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Pematangsiantar'),
  (gen_random_uuid(), 'Tanjungbalai', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Tanjungbalai'),
  (gen_random_uuid(), 'Sibolga', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Sibolga'),
  (gen_random_uuid(), 'Padang Sidimpuan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Padang+Sidimpuan'),
  (gen_random_uuid(), 'Gunungsitoli', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Gunungsitoli'),
  (gen_random_uuid(), 'Deli Serdang', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Deli+Serdang'),
  (gen_random_uuid(), 'Langkat', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Langkat'),
  (gen_random_uuid(), 'Karo', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Karo'),
  (gen_random_uuid(), 'Simalungun', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Simalungun'),
  (gen_random_uuid(), 'Asahan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Asahan'),
  (gen_random_uuid(), 'Labuhanbatu', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Labuhanbatu'),
  (gen_random_uuid(), 'Tapanuli Utara', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Tapanuli+Utara'),
  (gen_random_uuid(), 'Tapanuli Tengah', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Tapanuli+Tengah'),
  (gen_random_uuid(), 'Tapanuli Selatan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Tapanuli+Selatan'),
  (gen_random_uuid(), 'Mandailing Natal', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Mandailing+Natal'),
  (gen_random_uuid(), 'Nias', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Nias'),
  (gen_random_uuid(), 'Nias Barat', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Nias+Barat'),
  (gen_random_uuid(), 'Nias Selatan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Nias+Selatan'),
  (gen_random_uuid(), 'Nias Utara', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Nias+Utara'),
  (gen_random_uuid(), 'Samosir', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Samosir'),
  (gen_random_uuid(), 'Humbang Hasundutan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Humbang+Hasundutan'),
  (gen_random_uuid(), 'Pakpak Bharat', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Pakpak+Bharat'),
  (gen_random_uuid(), 'Padang Lawas', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Padang+Lawas'),
  (gen_random_uuid(), 'Padang Lawas Utara', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Padang+Lawas+Utara'),
  (gen_random_uuid(), 'Labuhanbatu Selatan', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Labuhanbatu+Selatan'),
  (gen_random_uuid(), 'Labuhanbatu Utara', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Labuhanbatu+Utara'),
  (gen_random_uuid(), 'Batubara', (SELECT id FROM provinces WHERE name = 'Sumatera Utara'), 'https://placehold.co/600x400.jpg?text=Batubara'),

  -- SUMATERA BARAT
  (gen_random_uuid(), 'Padang', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Padang'),
  (gen_random_uuid(), 'Bukittinggi', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Bukittinggi'),
  (gen_random_uuid(), 'Padang Panjang', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Padang+Panjang'),
  (gen_random_uuid(), 'Payakumbuh', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Payakumbuh'),
  (gen_random_uuid(), 'Sawahlunto', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Sawahlunto'),
  (gen_random_uuid(), 'Solok', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Solok'),
  (gen_random_uuid(), 'Pariaman', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Pariaman'),
  (gen_random_uuid(), 'Solok Selatan', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Solok+Selatan'),
  (gen_random_uuid(), 'Dharmasraya', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Dharmasraya'),
  (gen_random_uuid(), 'Pasaman', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Pasaman'),
  (gen_random_uuid(), 'Pasaman Barat', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Pasaman+Barat'),
  (gen_random_uuid(), 'Agam', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Agam'),
  (gen_random_uuid(), 'Lima Puluh Kota', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Lima+Puluh+Kota'),
  (gen_random_uuid(), 'Tanah Datar', (SELECT id FROM provinces WHERE name = 'Sumatera Barat'), 'https://placehold.co/600x400.jpg?text=Tanah+Datar'),

  -- RIAU
  (gen_random_uuid(), 'Pekanbaru', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Pekanbaru'),
  (gen_random_uuid(), 'Dumai', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Dumai'),
  (gen_random_uuid(), 'Kampar', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Kampar'),
  (gen_random_uuid(), 'Rokan Hulu', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Rokan+Hulu'),
  (gen_random_uuid(), 'Rokan Hilir', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Rokan+Hilir'),
  (gen_random_uuid(), 'Siak', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Siak'),
  (gen_random_uuid(), 'Bengkalis', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Bengkalis'),
  (gen_random_uuid(), 'Indragiri Hulu', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Indragiri+Hulu'),
  (gen_random_uuid(), 'Indragiri Hilir', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Indragiri+Hilir'),
  (gen_random_uuid(), 'Pelalawan', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Pelalawan'),
  (gen_random_uuid(), 'Kuantan Singingi', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Kuantan+Singingi'),
  (gen_random_uuid(), 'Meranti', (SELECT id FROM provinces WHERE name = 'Riau'), 'https://placehold.co/600x400.jpg?text=Meranti'),

  -- KEPULAUAN RIAU
  (gen_random_uuid(), 'Batam', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Batam'),
  (gen_random_uuid(), 'Tanjungpinang', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Tanjungpinang'),
  (gen_random_uuid(), 'Bintan', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Bintan'),
  (gen_random_uuid(), 'Karimun', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Karimun'),
  (gen_random_uuid(), 'Natuna', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Natuna'),
  (gen_random_uuid(), 'Lingga', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Lingga'),
  (gen_random_uuid(), 'Kepulauan Anambas', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Anambas'),
  (gen_random_uuid(), 'Tanjung Balai Karimun', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Tanjung+Balai+Karimun'),
  (gen_random_uuid(), 'Sei Raya', (SELECT id FROM provinces WHERE name = 'Kepulauan Riau'), 'https://placehold.co/600x400.jpg?text=Sei+Raya'),

  -- JAMBI
  (gen_random_uuid(), 'Jambi', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Jambi'),
  (gen_random_uuid(), 'Sungai Penuh', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Sungai+Penuh'),
  (gen_random_uuid(), 'Kerinci', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Kerinci'),
  (gen_random_uuid(), 'Merangin', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Merangin'),
  (gen_random_uuid(), 'Sarolangun', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Sarolangun'),
  (gen_random_uuid(), 'Batang Hari', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Batang+Hari'),
  (gen_random_uuid(), 'Muaro Jambi', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Muaro+Jambi'),
  (gen_random_uuid(), 'Tanjung Jabung Timur', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Tanjung+Jabung+Timur'),
  (gen_random_uuid(), 'Tanjung Jabung Barat', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Tanjung+Jabung+Barat'),
  (gen_random_uuid(), 'Tebo', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Tebo'),
  (gen_random_uuid(), 'Bungo', (SELECT id FROM provinces WHERE name = 'Jambi'), 'https://placehold.co/600x400.jpg?text=Bungo'),

  -- SUMATERA SELATAN
  (gen_random_uuid(), 'Palembang', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Palembang'),
  (gen_random_uuid(), 'Prabumulih', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Prabumulih'),
  (gen_random_uuid(), 'Pagar Alam', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Pagar+Alam'),
  (gen_random_uuid(), 'Lubuklinggau', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Lubuklinggau'),
  (gen_random_uuid(), 'Muara Enim', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Muara+Enim'),
  (gen_random_uuid(), 'Lahat', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Lahat'),
  (gen_random_uuid(), 'Musi Rawas', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Musi+Rawas'),
  (gen_random_uuid(), 'Musi Banyuasin', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Musi+Banyuasin'),
  (gen_random_uuid(), 'Banyuasin', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Banyuasin'),
  (gen_random_uuid(), 'Ogan Komering Ulu', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Ogan+Komering+Ulu'),
  (gen_random_uuid(), 'Ogan Komering Ilir', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Ogan+Komering+Ilir'),
  (gen_random_uuid(), 'Ogan Ilir', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Ogan+Ilir'),
  (gen_random_uuid(), 'Empat Lawang', (SELECT id FROM provinces WHERE name = 'Sumatera Selatan'), 'https://placehold.co/600x400.jpg?text=Empat+Lawang'),

  -- BENGKULU
  (gen_random_uuid(), 'Bengkulu', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Bengkulu'),
  (gen_random_uuid(), 'Rejang Lebong', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Rejang+Lebong'),
  (gen_random_uuid(), 'Bengkulu Selatan', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Bengkulu+Selatan'),
  (gen_random_uuid(), 'Bengkulu Utara', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Bengkulu+Utara'),
  (gen_random_uuid(), 'Kaur', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Kaur'),
  (gen_random_uuid(), 'Seluma', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Seluma'),
  (gen_random_uuid(), 'Mukomuko', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Mukomuko'),
  (gen_random_uuid(), 'Lebong', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Lebong'),
  (gen_random_uuid(), 'Kepahiang', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Kepahiang'),
  (gen_random_uuid(), 'Bengkulu Tengah', (SELECT id FROM provinces WHERE name = 'Bengkulu'), 'https://placehold.co/600x400.jpg?text=Bengkulu+Tengah'),

  -- LAMPUNG
  (gen_random_uuid(), 'Bandar Lampung', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Bandar+Lampung'),
  (gen_random_uuid(), 'Metro', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Metro'),
  (gen_random_uuid(), 'Lampung Selatan', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Lampung+Selatan'),
  (gen_random_uuid(), 'Lampung Tengah', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Lampung+Tengah'),
  (gen_random_uuid(), 'Lampung Utara', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Lampung+Utara'),
  (gen_random_uuid(), 'Lampung Barat', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Lampung+Barat'),
  (gen_random_uuid(), 'Tulang Bawang', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Tulang+Bawang'),
  (gen_random_uuid(), 'Tanggamus', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Tanggamus'),
  (gen_random_uuid(), 'Lampung Timur', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Lampung+Timur'),
  (gen_random_uuid(), 'Way Kanan', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Way+Kanan'),
  (gen_random_uuid(), 'Pesawaran', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Pesawaran'),
  (gen_random_uuid(), 'Pringsewu', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Pringsewu'),
  (gen_random_uuid(), 'Tulang Bawang Barat', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Tulang+Bawang+Barat'),
  (gen_random_uuid(), 'Mesuji', (SELECT id FROM provinces WHERE name = 'Lampung'), 'https://placehold.co/600x400.jpg?text=Mesuji'),

  -- KEPULAUAN BANGKA BELITUNG
  (gen_random_uuid(), 'Pangkalpinang', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Pangkalpinang'),
  (gen_random_uuid(), 'Bangka Barat', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Bangka+Barat'),
  (gen_random_uuid(), 'Bangka Tengah', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Bangka+Tengah'),
  (gen_random_uuid(), 'Bangka Selatan', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Bangka+Selatan'),
  (gen_random_uuid(), 'Belitung', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Belitung'),
  (gen_random_uuid(), 'Belitung Timur', (SELECT id FROM provinces WHERE name = 'Kepulauan Bangka Belitung'), 'https://placehold.co/600x400.jpg?text=Belitung+Timur'),

  -- DKI JAKARTA
  (gen_random_uuid(), 'Jakarta Pusat', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Jakarta+Pusat'),
  (gen_random_uuid(), 'Jakarta Utara', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Jakarta+Utara'),
  (gen_random_uuid(), 'Jakarta Barat', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Jakarta+Barat'),
  (gen_random_uuid(), 'Jakarta Selatan', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Jakarta+Selatan'),
  (gen_random_uuid(), 'Jakarta Timur', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Jakarta+Timur'),
  (gen_random_uuid(), 'Kepulauan Seribu', (SELECT id FROM provinces WHERE name = 'DKI Jakarta'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Seribu'),

  -- JAWA BARAT
  (gen_random_uuid(), 'Bandung', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Bandung'),
  (gen_random_uuid(), 'Bogor', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Bogor'),
  (gen_random_uuid(), 'Bekasi', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Bekasi'),
  (gen_random_uuid(), 'Depok', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Depok'),
  (gen_random_uuid(), 'Cirebon', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Cirebon'),
  (gen_random_uuid(), 'Sukabumi', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Sukabumi'),
  (gen_random_uuid(), 'Tasikmalaya', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Tasikmalaya'),
  (gen_random_uuid(), 'Cimahi', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Cimahi'),
  (gen_random_uuid(), 'Banjar', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Banjar'),
  (gen_random_uuid(), 'Garut', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Garut'),
  (gen_random_uuid(), 'Ciamis', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Ciamis'),
  (gen_random_uuid(), 'Kuningan', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Kuningan'),
  (gen_random_uuid(), 'Majalengka', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Majalengka'),
  (gen_random_uuid(), 'Indramayu', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Indramayu'),
  (gen_random_uuid(), 'Subang', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Subang'),
  (gen_random_uuid(), 'Purwakarta', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Purwakarta'),
  (gen_random_uuid(), 'Karawang', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Karawang'),
  (gen_random_uuid(), 'Cianjur', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Cianjur'),
  (gen_random_uuid(), 'Pangandaran', (SELECT id FROM provinces WHERE name = 'Jawa Barat'), 'https://placehold.co/600x400.jpg?text=Pangandaran'),

  -- JAWA TENGAH
  (gen_random_uuid(), 'Semarang', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Semarang'),
  (gen_random_uuid(), 'Surakarta', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Surakarta'),
  (gen_random_uuid(), 'Magelang', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Magelang'),
  (gen_random_uuid(), 'Salatiga', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Salatiga'),
  (gen_random_uuid(), 'Pekalongan', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Pekalongan'),
  (gen_random_uuid(), 'Cilacap', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Cilacap'),
  (gen_random_uuid(), 'Purwokerto', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Purwokerto'),
  (gen_random_uuid(), 'Klaten', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Klaten'),
  (gen_random_uuid(), 'Kudus', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Kudus'),
  (gen_random_uuid(), 'Purworejo', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Purworejo'),
  (gen_random_uuid(), 'Pati', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Pati'),
  (gen_random_uuid(), 'Pemalang', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Pemalang'),
  (gen_random_uuid(), 'Purbalingga', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Purbalingga'),
  (gen_random_uuid(), 'Banjarnegara', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Banjarnegara'),
  (gen_random_uuid(), 'Kebumen', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Kebumen'),
  (gen_random_uuid(), 'Wonosobo', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Wonosobo'),
  (gen_random_uuid(), 'Temanggung', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Temanggung'),
  (gen_random_uuid(), 'Kendal', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Kendal'),
  (gen_random_uuid(), 'Batang', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Batang'),
  (gen_random_uuid(), 'Brebes', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Brebes'),
  (gen_random_uuid(), 'Tegal', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Tegal'),
  (gen_random_uuid(), 'Sukoharjo', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Sukoharjo'),
  (gen_random_uuid(), 'Karanganyar', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Karanganyar'),
  (gen_random_uuid(), 'Wonogiri', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Wonogiri'),
  (gen_random_uuid(), 'Sragen', (SELECT id FROM provinces WHERE name = 'Jawa Tengah'), 'https://placehold.co/600x400.jpg?text=Sragen'),

  -- DI YOGYAKARTA
  (gen_random_uuid(), 'Yogyakarta', (SELECT id FROM provinces WHERE name = 'DI Yogyakarta'), 'https://placehold.co/600x400.jpg?text=Yogyakarta'),
  (gen_random_uuid(), 'Sleman', (SELECT id FROM provinces WHERE name = 'DI Yogyakarta'), 'https://placehold.co/600x400.jpg?text=Sleman'),
  (gen_random_uuid(), 'Bantul', (SELECT id FROM provinces WHERE name = 'DI Yogyakarta'), 'https://placehold.co/600x400.jpg?text=Bantul'),
  (gen_random_uuid(), 'Kulon Progo', (SELECT id FROM provinces WHERE name = 'DI Yogyakarta'), 'https://placehold.co/600x400.jpg?text=Kulon+Progo'),
  (gen_random_uuid(), 'Gunung Kidul', (SELECT id FROM provinces WHERE name = 'DI Yogyakarta'), 'https://placehold.co/600x400.jpg?text=Gunung+Kidul'),

  -- JAWA TIMUR (continued from where it was cut off)
  (gen_random_uuid(), 'Surabaya', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Surabaya'),
  (gen_random_uuid(), 'Malang', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Malang'),
  (gen_random_uuid(), 'Kediri', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Kediri'),
  (gen_random_uuid(), 'Blitar', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Blitar'),
  (gen_random_uuid(), 'Mojokerto', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Mojokerto'),
  (gen_random_uuid(), 'Madiun', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Madiun'),
  (gen_random_uuid(), 'Pasuruan', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Pasuruan'),
  (gen_random_uuid(), 'Probolinggo', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Probolinggo'),
  (gen_random_uuid(), 'Batu', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Batu'),
  (gen_random_uuid(), 'Jember', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Jember'),
  (gen_random_uuid(), 'Lumajang', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Lumajang'),
  (gen_random_uuid(), 'Bondowoso', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Bondowoso'),
  (gen_random_uuid(), 'Situbondo', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Situbondo'),
  (gen_random_uuid(), 'Banyuwangi', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Banyuwangi'),
  (gen_random_uuid(), 'Tulungagung', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Tulungagung'),
  (gen_random_uuid(), 'Trenggalek', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Trenggalek'),
  (gen_random_uuid(), 'Ponorogo', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Ponorogo'),
  (gen_random_uuid(), 'Magetan', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Magetan'),
  
  -- Additional cities for Jawa Timur based on actual data
  (gen_random_uuid(), 'Ngawi', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Ngawi'),
  (gen_random_uuid(), 'Pacitan', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Pacitan'),
  (gen_random_uuid(), 'Bojonegoro', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Bojonegoro'),
  (gen_random_uuid(), 'Tuban', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Tuban'),
  (gen_random_uuid(), 'Lamongan', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Lamongan'),
  (gen_random_uuid(), 'Gresik', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Gresik'),
  (gen_random_uuid(), 'Sidoarjo', (SELECT id FROM provinces WHERE name = 'Jawa Timur'), 'https://placehold.co/600x400.jpg?text=Sidoarjo'),

  -- BANTEN
  (gen_random_uuid(), 'Serang', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Serang'),
  (gen_random_uuid(), 'Tangerang', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Tangerang'),
  (gen_random_uuid(), 'Tangerang Selatan', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Tangerang+Selatan'),
  (gen_random_uuid(), 'Cilegon', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Cilegon'),
  (gen_random_uuid(), 'Pandeglang', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Pandeglang'),
  (gen_random_uuid(), 'Lebak', (SELECT id FROM provinces WHERE name = 'Banten'), 'https://placehold.co/600x400.jpg?text=Lebak'),

  -- BALI
  (gen_random_uuid(), 'Denpasar', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Denpasar'),
  (gen_random_uuid(), 'Badung', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Badung'),
  (gen_random_uuid(), 'Gianyar', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Gianyar'),
  (gen_random_uuid(), 'Tabanan', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Tabanan'),
  (gen_random_uuid(), 'Klungkung', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Klungkung'),
  (gen_random_uuid(), 'Bangli', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Bangli'),
  (gen_random_uuid(), 'Karangasem', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Karangasem'),
  (gen_random_uuid(), 'Buleleng', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Buleleng'),
  (gen_random_uuid(), 'Jembrana', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Jembrana'),
  (gen_random_uuid(), 'Singaraja', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Singaraja'),
  (gen_random_uuid(), 'Negara', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Negara'),
  (gen_random_uuid(), 'Amlapura', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Amlapura'),
  (gen_random_uuid(), 'Semarapura', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Semarapura'),
  (gen_random_uuid(), 'Ubud', (SELECT id FROM provinces WHERE name = 'Bali'), 'https://placehold.co/600x400.jpg?text=Ubud'),

  -- NUSA TENGGARA BARAT
  (gen_random_uuid(), 'Mataram', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Mataram'),
  (gen_random_uuid(), 'Bima', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Bima'),
  (gen_random_uuid(), 'Lombok Barat', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Lombok+Barat'),
  (gen_random_uuid(), 'Lombok Tengah', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Lombok+Tengah'),
  (gen_random_uuid(), 'Lombok Timur', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Lombok+Timur'),
  (gen_random_uuid(), 'Lombok Utara', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Lombok+Utara'),
  (gen_random_uuid(), 'Sumbawa', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Sumbawa'),
  (gen_random_uuid(), 'Sumbawa Barat', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Sumbawa+Barat'),
  (gen_random_uuid(), 'Dompu', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Barat'), 'https://placehold.co/600x400.jpg?text=Dompu'),

  -- NUSA TENGGARA TIMUR
  (gen_random_uuid(), 'Kupang', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Kupang'),
  (gen_random_uuid(), 'Ende', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Ende'),
  (gen_random_uuid(), 'Manggarai', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Manggarai'),
  (gen_random_uuid(), 'Timor Tengah Selatan', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Timor+Tengah+Selatan'),
  (gen_random_uuid(), 'Timor Tengah Utara', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Timor+Tengah+Utara'),
  (gen_random_uuid(), 'Belu', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Belu'),
  (gen_random_uuid(), 'Alor', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Alor'),
  (gen_random_uuid(), 'Flores Timur', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Flores+Timur'),
  (gen_random_uuid(), 'Sikka', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Sikka'),
  (gen_random_uuid(), 'Ngada', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Ngada'),
  (gen_random_uuid(), 'Sumba Barat', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Sumba+Barat'),
  (gen_random_uuid(), 'Sumba Timur', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Sumba+Timur'),
  (gen_random_uuid(), 'Lembata', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Lembata'),
  (gen_random_uuid(), 'Rote Ndao', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Rote+Ndao'),
  (gen_random_uuid(), 'Sabu Raijua', (SELECT id FROM provinces WHERE name = 'Nusa Tenggara Timur'), 'https://placehold.co/600x400.jpg?text=Sabu+Raijua'),

  -- KALIMANTAN BARAT
  (gen_random_uuid(), 'Pontianak', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Pontianak'),
  (gen_random_uuid(), 'Singkawang', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Singkawang'),
  (gen_random_uuid(), 'Sambas', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Sambas'),
  (gen_random_uuid(), 'Bengkayang', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Bengkayang'),
  (gen_random_uuid(), 'Landak', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Landak'),
  (gen_random_uuid(), 'Mempawah', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Mempawah'),
  (gen_random_uuid(), 'Sanggau', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Sanggau'),
  (gen_random_uuid(), 'Ketapang', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Ketapang'),
  (gen_random_uuid(), 'Sintang', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Sintang'),
  (gen_random_uuid(), 'Kapuas Hulu', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Kapuas+Hulu'),
  (gen_random_uuid(), 'Sekadau', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Sekadau'),
  (gen_random_uuid(), 'Melawi', (SELECT id FROM provinces WHERE name = 'Kalimantan Barat'), 'https://placehold.co/600x400.jpg?text=Melawi'),

  -- KALIMANTAN TENGAH
  (gen_random_uuid(), 'Palangka Raya', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Palangka+Raya'),
  (gen_random_uuid(), 'Kapuas', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Kapuas'),
  (gen_random_uuid(), 'Barito Selatan', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Barito+Selatan'),
  (gen_random_uuid(), 'Barito Utara', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Barito+Utara'),
  (gen_random_uuid(), 'Sukamara', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Sukamara'),
  (gen_random_uuid(), 'Lamandau', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Lamandau'),
  (gen_random_uuid(), 'Seruyan', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Seruyan'),
  (gen_random_uuid(), 'Katingan', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Katingan'),
  (gen_random_uuid(), 'Pulang Pisau', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Pulang+Pisau'),
  (gen_random_uuid(), 'Gunung Mas', (SELECT id FROM provinces WHERE name = 'Kalimantan Tengah'), 'https://placehold.co/600x400.jpg?text=Gunung+Mas'),

  -- KALIMANTAN SELATAN
  (gen_random_uuid(), 'Banjarmasin', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Banjarmasin'),
  (gen_random_uuid(), 'Banjarbaru', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Banjarbaru'),
  (gen_random_uuid(), 'Tanah Laut', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Tanah+Laut'),
  (gen_random_uuid(), 'Kotabaru', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Kotabaru'),
  (gen_random_uuid(), 'Banjar', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Banjar'),
  (gen_random_uuid(), 'Barito Kuala', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Barito+Kuala'),
  (gen_random_uuid(), 'Tapin', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Tapin'),
  (gen_random_uuid(), 'Hulu Sungai Selatan', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Hulu+Sungai+Selatan'),
  (gen_random_uuid(), 'Hulu Sungai Tengah', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Hulu+Sungai+Tengah'),
  (gen_random_uuid(), 'Hulu Sungai Utara', (SELECT id FROM provinces WHERE name = 'Kalimantan Selatan'), 'https://placehold.co/600x400.jpg?text=Hulu+Sungai+Utara'),

  -- KALIMANTAN TIMUR
  (gen_random_uuid(), 'Samarinda', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Samarinda'),
  (gen_random_uuid(), 'Balikpapan', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Balikpapan'),
  (gen_random_uuid(), 'Bontang', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Bontang'),
  (gen_random_uuid(), 'Kutai Kartanegara', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Kutai+Kartanegara'),
  (gen_random_uuid(), 'Kutai Barat', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Kutai+Barat'),
  (gen_random_uuid(), 'Kutai Timur', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Kutai+Timur'),
  (gen_random_uuid(), 'Berau', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Berau'),
  (gen_random_uuid(), 'Paser', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Paser'),
  (gen_random_uuid(), 'Penajam Paser Utara', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Penajam+Paser+Utara'),
  (gen_random_uuid(), 'Mahakam Ulu', (SELECT id FROM provinces WHERE name = 'Kalimantan Timur'), 'https://placehold.co/600x400.jpg?text=Mahakam+Ulu'),

  -- KALIMANTAN UTARA
  (gen_random_uuid(), 'Tarakan', (SELECT id FROM provinces WHERE name = 'Kalimantan Utara'), 'https://placehold.co/600x400.jpg?text=Tarakan'),
  (gen_random_uuid(), 'Bulungan', (SELECT id FROM provinces WHERE name = 'Kalimantan Utara'), 'https://placehold.co/600x400.jpg?text=Bulungan'),
  (gen_random_uuid(), 'Malinau', (SELECT id FROM provinces WHERE name = 'Kalimantan Utara'), 'https://placehold.co/600x400.jpg?text=Malinau'),
  (gen_random_uuid(), 'Nunukan', (SELECT id FROM provinces WHERE name = 'Kalimantan Utara'), 'https://placehold.co/600x400.jpg?text=Nunukan'),
  (gen_random_uuid(), 'Tana Tidung', (SELECT id FROM provinces WHERE name = 'Kalimantan Utara'), 'https://placehold.co/600x400.jpg?text=Tana+Tidung'),

  -- SULAWESI UTARA
  (gen_random_uuid(), 'Manado', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Manado'),
  (gen_random_uuid(), 'Bitung', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Bitung'),
  (gen_random_uuid(), 'Tomohon', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Tomohon'),
  (gen_random_uuid(), 'Kotamobagu', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Kotamobagu'),
  (gen_random_uuid(), 'Minahasa', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Minahasa'),
  (gen_random_uuid(), 'Minahasa Selatan', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Minahasa+Selatan'),
  (gen_random_uuid(), 'Minahasa Utara', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Minahasa+Utara'),
  (gen_random_uuid(), 'Minahasa Tenggara', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Minahasa+Tenggara'),
  (gen_random_uuid(), 'Bolaang Mongondow', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Bolaang+Mongondow'),
  (gen_random_uuid(), 'Kepulauan Sangihe', (SELECT id FROM provinces WHERE name = 'Sulawesi Utara'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Sangihe'),

  -- SULAWESI TENGAH
  (gen_random_uuid(), 'Palu', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Palu'),
  (gen_random_uuid(), 'Donggala', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Donggala'),
  (gen_random_uuid(), 'Toli-Toli', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Toli-Toli'),
  (gen_random_uuid(), 'Buol', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Buol'),
  (gen_random_uuid(), 'Parigi Moutong', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Parigi+Moutong'),
  (gen_random_uuid(), 'Poso', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Poso'),
  (gen_random_uuid(), 'Banggai', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Banggai'),
  (gen_random_uuid(), 'Banggai Kepulauan', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Banggai+Kepulauan'),
  (gen_random_uuid(), 'Morowali', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Morowali'),
  (gen_random_uuid(), 'Tojo Una-Una', (SELECT id FROM provinces WHERE name = 'Sulawesi Tengah'), 'https://placehold.co/600x400.jpg?text=Tojo+Una-Una'),

  -- SULAWESI SELATAN
  (gen_random_uuid(), 'Makassar', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Makassar'),
  (gen_random_uuid(), 'Parepare', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Parepare'),
  (gen_random_uuid(), 'Palopo', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Palopo'),
  (gen_random_uuid(), 'Maros', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Maros'),
  (gen_random_uuid(), 'Gowa', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Gowa'),
  (gen_random_uuid(), 'Takalar', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Takalar'),
  (gen_random_uuid(), 'Jeneponto', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Jeneponto'),
  (gen_random_uuid(), 'Bantaeng', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Bantaeng'),
  (gen_random_uuid(), 'Bulukumba', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Bulukumba'),
  (gen_random_uuid(), 'Bone', (SELECT id FROM provinces WHERE name = 'Sulawesi Selatan'), 'https://placehold.co/600x400.jpg?text=Bone'),

  -- SULAWESI TENGGARA
  (gen_random_uuid(), 'Kendari', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Kendari'),
  (gen_random_uuid(), 'Bau-Bau', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Bau-Bau'),
  (gen_random_uuid(), 'Konawe', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Konawe'),
  (gen_random_uuid(), 'Kolaka', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Kolaka'),
  (gen_random_uuid(), 'Konawe Selatan', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Konawe+Selatan'),
  (gen_random_uuid(), 'Bombana', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Bombana'),
  (gen_random_uuid(), 'Wakatobi', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Wakatobi'),
  (gen_random_uuid(), 'Kolaka Utara', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Kolaka+Utara'),
  (gen_random_uuid(), 'Buton', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Buton'),
  (gen_random_uuid(), 'Muna', (SELECT id FROM provinces WHERE name = 'Sulawesi Tenggara'), 'https://placehold.co/600x400.jpg?text=Muna'),

  -- GORONTALO
  (gen_random_uuid(), 'Gorontalo', (SELECT id FROM provinces WHERE name = 'Gorontalo'), 'https://placehold.co/600x400.jpg?text=Gorontalo'),
  (gen_random_uuid(), 'Gorontalo Utara', (SELECT id FROM provinces WHERE name = 'Gorontalo'), 'https://placehold.co/600x400.jpg?text=Gorontalo+Utara'),
  (gen_random_uuid(), 'Bone Bolango', (SELECT id FROM provinces WHERE name = 'Gorontalo'), 'https://placehold.co/600x400.jpg?text=Bone+Bolango'),
  (gen_random_uuid(), 'Pohuwato', (SELECT id FROM provinces WHERE name = 'Gorontalo'), 'https://placehold.co/600x400.jpg?text=Pohuwato'),
  -- GORONTALO (continuing from cutoff)
  (gen_random_uuid(), 'Boalemo', (SELECT id FROM provinces WHERE name = 'Gorontalo'), 'https://placehold.co/600x400.jpg?text=Boalemo'),

  -- SULAWESI BARAT
  (gen_random_uuid(), 'Mamuju', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Mamuju'),
  (gen_random_uuid(), 'Majene', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Majene'),
  (gen_random_uuid(), 'Polewali Mandar', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Polewali+Mandar'),
  (gen_random_uuid(), 'Mamasa', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Mamasa'),
  (gen_random_uuid(), 'Mamuju Utara', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Mamuju+Utara'),
  (gen_random_uuid(), 'Pasangkayu', (SELECT id FROM provinces WHERE name = 'Sulawesi Barat'), 'https://placehold.co/600x400.jpg?text=Pasangkayu'),

  -- MALUKU
  (gen_random_uuid(), 'Ambon', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Ambon'),
  (gen_random_uuid(), 'Tual', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Tual'),
  (gen_random_uuid(), 'Maluku Tengah', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Maluku+Tengah'),
  (gen_random_uuid(), 'Buru', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Buru'),
  (gen_random_uuid(), 'Kepulauan Aru', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Aru'),
  (gen_random_uuid(), 'Seram Bagian Barat', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Seram+Bagian+Barat'),
  (gen_random_uuid(), 'Seram Bagian Timur', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Seram+Bagian+Timur'),
  (gen_random_uuid(), 'Maluku Tenggara', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Maluku+Tenggara'),
  (gen_random_uuid(), 'Maluku Tenggara Barat', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Maluku+Tenggara+Barat'),
  (gen_random_uuid(), 'Buru Selatan', (SELECT id FROM provinces WHERE name = 'Maluku'), 'https://placehold.co/600x400.jpg?text=Buru+Selatan'),

  -- MALUKU UTARA
  (gen_random_uuid(), 'Ternate', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Ternate'),
  (gen_random_uuid(), 'Tidore Kepulauan', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Tidore+Kepulauan'),
  (gen_random_uuid(), 'Halmahera Barat', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Halmahera+Barat'),
  (gen_random_uuid(), 'Halmahera Tengah', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Halmahera+Tengah'),
  (gen_random_uuid(), 'Kepulauan Sula', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Sula'),
  (gen_random_uuid(), 'Halmahera Selatan', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Halmahera+Selatan'),
  (gen_random_uuid(), 'Halmahera Utara', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Halmahera+Utara'),
  (gen_random_uuid(), 'Halmahera Timur', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Halmahera+Timur'),
  (gen_random_uuid(), 'Pulau Morotai', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Pulau+Morotai'),
  (gen_random_uuid(), 'Pulau Taliabu', (SELECT id FROM provinces WHERE name = 'Maluku Utara'), 'https://placehold.co/600x400.jpg?text=Pulau+Taliabu'),

  -- PAPUA BARAT
  (gen_random_uuid(), 'Manokwari', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Manokwari'),
  (gen_random_uuid(), 'Sorong', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Sorong'),
  (gen_random_uuid(), 'Fakfak', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Fakfak'),
  (gen_random_uuid(), 'Kaimana', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Kaimana'),
  (gen_random_uuid(), 'Manokwari Selatan', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Manokwari+Selatan'),
  (gen_random_uuid(), 'Pegunungan Arfak', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Pegunungan+Arfak'),
  (gen_random_uuid(), 'Raja Ampat', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Raja+Ampat'),
  (gen_random_uuid(), 'Sorong Selatan', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Sorong+Selatan'),
  (gen_random_uuid(), 'Maybrat', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Maybrat'),
  (gen_random_uuid(), 'Tambrauw', (SELECT id FROM provinces WHERE name = 'Papua Barat'), 'https://placehold.co/600x400.jpg?text=Tambrauw'),

  -- PAPUA
  (gen_random_uuid(), 'Jayapura', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Jayapura'),
  (gen_random_uuid(), 'Biak Numfor', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Biak+Numfor'),
  (gen_random_uuid(), 'Nabire', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Nabire'),
  (gen_random_uuid(), 'Kepulauan Yapen', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Kepulauan+Yapen'),
  (gen_random_uuid(), 'Merauke', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Merauke'),
  (gen_random_uuid(), 'Jayawijaya', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Jayawijaya'),
  (gen_random_uuid(), 'Yahukimo', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Yahukimo'),
  (gen_random_uuid(), 'Tolikara', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Tolikara'),
  (gen_random_uuid(), 'Sarmi', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Sarmi'),
  (gen_random_uuid(), 'Keerom', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Keerom'),
  (gen_random_uuid(), 'Waropen', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Waropen'),
  (gen_random_uuid(), 'Boven Digoel', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Boven+Digoel'),
  (gen_random_uuid(), 'Mappi', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Mappi'),
  (gen_random_uuid(), 'Asmat', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Asmat'),
  (gen_random_uuid(), 'Supiori', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Supiori'),
  (gen_random_uuid(), 'Mamberamo Raya', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Mamberamo+Raya'),
  (gen_random_uuid(), 'Mamberamo Tengah', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Mamberamo+Tengah'),
  (gen_random_uuid(), 'Yalimo', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Yalimo'),
  (gen_random_uuid(), 'Lanny Jaya', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Lanny+Jaya'),
  (gen_random_uuid(), 'Nduga', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Nduga'),
  (gen_random_uuid(), 'Puncak', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Puncak'),
  (gen_random_uuid(), 'Dogiyai', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Dogiyai'),
  (gen_random_uuid(), 'Intan Jaya', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Intan+Jaya'),
  (gen_random_uuid(), 'Deiyai', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Deiyai'),
  (gen_random_uuid(), 'Paniai', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Paniai'),
  (gen_random_uuid(), 'Mimika', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Mimika'),
  (gen_random_uuid(), 'Puncak Jaya', (SELECT id FROM provinces WHERE name = 'Papua'), 'https://placehold.co/600x400.jpg?text=Puncak+Jaya')

-- Note: Added semicolon to properly end the INSERT statement
;

-- Verify the insertion
SELECT COUNT(*) as total_cities FROM public.cities;